### ISSUE TITLE
Sample over names(batch_per_bucket)

### ISSUE THREAD

**Issue by thirdwing** [jeremiedb/mxnet_R_bucketing#1]
What is the purpose of shuffling here?

https://github.com/jeremiedb/mxnet_R_bucketing/blob/master/mx_io_bucket_iter.R#L38

**Comment by jeremiedb** [comment]
It's meant to randomize from which buckets each batch will be taken. So the shuffling is 2-stage: shuffle the buckets ordering and shuffle the samples within each bucket. 
This bucket shuffing should only be applied when `shuffle=T` though. I've just pushed a dev branch which bring this correction, remove the unnecessary init() function and also support GRU cell.

**Comment by thirdwing** [comment]
Thanks!
