### ISSUE TITLE
Question on embedding layer

### ISSUE THREAD

**Issue by bmkor** [jeremiedb/mxnet_R_bucketing#3]
I got problem in understanding the purpose of the embedding layer (corresponding to the para num.embed in rnn.graph). Could I ask what's its purpose and could I set it to be any arbitrary non-negative integer? Thanks a lot.

**Comment by jeremiedb** [comment]
The embedding layer performs the vectorization. Let's say the  input data is made of a vocabulary of 1000 words, then each sequence would be a vector of integers from 0 to 999, one integer for each word. Working on such high dimensionality is impractical, so the embedding reproject each word into a defined number of dimensions. This number of dimensions is arbitrary, could be 2 or 300 like for some Word2Vec or Glove embeddings. After the application of the embedding, a sequence of length N is transformed from a vector of N integers into a matrix of floats of dimension num.embed X N.

**Comment by bmkor** [comment]
Thank you very much. So it is projecting the non negative integer vector to a subspace (I think) in a higher dimension.

I got another question and it is not related to embedding layer.  Could I close this issue and reopen one or just ask here?
